config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
import board.views

import reply.views
import user.views
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls), #관리자 페이지
    path('', user.views.mainpage), #메인페이지로 url이 입력되지 않은 상태
    path('ex', user.views.mainindex), #부트스트랩 참조용

    #게시판
    path('board/getdata', board.views.createBoardGet), #게시물 등록
    path('board/readlist', board.views.readlist), #게시물 리스트
    path('board/readdata/<int:bid>', board.views.readdata), # 단일 게시물
    path('board/deleteget/<int:bid>',board.views.deleteget), #게시물 삭제
    path('board/updateget/<int:bid>',board.views.updateget), # 게시물 수정
    #댓글
    path('reply/createreply/<int:bid>', reply.views.createreply), #댓글 등록
    #path('reply/readreplylist', reply.views.readreplylist), #댓글 리스트/ 현재 사용 x
    #path('reply/readreply/<int:bid>', reply.views.readreply), # 단일 댓글 / 현재 사용 x
    path('reply/deletereply/<int:bid>', reply.views.deletereply), # 댓글 삭제
    path('reply/updatereply/<int:bid>', reply.views.updatereply), # 댓글 수정
    #회원가입 실습_자체구현 코드_현재 allauth 사용하므로 사용 x
    #path('user/signup', user.views.signup),
    #path('user/login', user.views.login),
    #path('user/logout', user.views.logout),
    #좋아요 기능
    path('like/<int:bid>',board.views.like),
    #Kakao 로그인 redirect url
    #path('oauth/redirect2',user.views.kakaologin),
    #ALLAUTH
    path('accounts/',include('allauth.urls')), #allauth의 url을 모두 사용
    path('accounts/profile/',user.views.mainpage), #로그인하면 메인페이지로 이동/ 혹 마이페이지로 변경 예정
    #마이페이지
    path('user/mypage', user.views.mypage),


] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

board/models.py
from django.contrib.auth.models import User
from django.db import models
from user.models import User
# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=100)
    contents = models.TextField()
    create_date = models.DateTimeField(auto_now_add = True)
    writer = models.ForeignKey(User,on_delete=models.CASCADE)
    #user은 Django에서 제공해주는 model,즉 writer는 user을 참조한다. 이 user는 무결성 참조조건에 의해 존재하는 값 혹은 null 값 만 써야한다
    #참조하는 user가 삭제될 때 게시글을 남기거나 삭제하는 옵션 = on_delete, CASCADE = 삭제
    like = models.ManyToManyField(User, related_name="likes", blank=True)


class PostImage(models.Model):
    image = models.ImageField(upload_to= 'images/', null=True, blank =True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

reply/models.py
from django.contrib.auth.models import User
from django.db import models
from board.models import Post
from user.models import User

class Reply(models.Model):
    contents = models.TextField()
    create_date = models.DateTimeField(auto_now_add=True)
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

board/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render, redirect

# Create your views here.
from board.form import PostForm
from board.models import Post, PostImage
from reply.form import Replyform


@login_required(login_url = '/accounts/login/')
def createBoardGet(request):
    if request.method == "GET":
        return render(request, "board/getdata.html")
    elif request.method == "POST":
        postForm = PostForm(request.POST)# form data를 form instance에 저장
        if postForm.is_valid():  # 유효성 검증
            post = postForm.save(commit=False)# 원래 save하면 db에 저장되는데, 이를 false로 하면 저장을 안하고,DB 객체를 반환한다. 중복데이터나 오류를 미리 알아낼 수 있게 해줌
            post.writer = request.user #작성자 설정, 이 설정을 안하면 writer를 form에서 exclude했기에 유효성 검사는 통과하지만 null값이 들어간다
            post.save()

            for image in request.FILES.getlist('image',None):
                postimage = PostImage()
                postimage.image = image
                postimage.post = post
                postimage.save()
        return redirect('readdata/'+str(post.id))

def readlist(request): #전체 리스트
    #ids = request.Get.get('id',None) #get방식으로 주소창에 원하는 id를 입력받음
    board_get_data = Post.objects.prefetch_related('postimage_set').all().order_by('-id') #id오름차순으로 정렬
    image = PostImage.objects.all()
    context = {
       'datas': board_get_data,
    }
    return render(request, "board/readlist.html", context)

@login_required(login_url = '/accounts/login/')
def readmylist(request): #사용자가 작성한 리스트
    board_get_data = Post.objects.prefetch_related('postimage_set').filter(writer_id=request.user.id).order_by('-id') #id오름차순으로 정렬
    context = {
       'datas': board_get_data,
    }
    return render(request, "board/readlist.html", context)

def readdata(request, bid): #단일 게시물
    # prefetch_related
    post = Post.objects.prefetch_related('reply_set','postimage_set').get(id=bid) #reply 요소가 reply_set으로 들어감
    replyform = Replyform()
    context = {'post': post, 'replyform':replyform}

    return render(request, 'reply/createreply.html', context)

@login_required(login_url = '/accounts/login/')
def deleteget(request, bid):
    post = Post.objects.get(id=bid)
    if request.user != post.writer:
        return redirect('/board/readlist')
    else:
        post.delete()
        return redirect('/board/readlist')

@login_required(login_url = '/accounts/login/')
def updateget(request, bid):
    post = Post.objects.get(id=bid)
    if request.user != post.writer:
        return redirect('/board/readlist')
    else:
        if request.method == "GET":
            context = {'post':post}
            return render(request, "board/updatedata.html", context)
        elif request.method == "POST":
            postForm = PostForm(request.POST, instance=post)
            if postForm.is_valid():
                post = postForm.save(commit=False)
                post.save()
                for image in request.FILES.getlist('image', None):
                    postimage = PostImage()
                    postimage.image = image
                    postimage.post = post
                    postimage.save()
                return redirect('/board/readdata/' + str(bid))

@login_required(login_url = '/accounts/login/')
def like(request,bid):
    post = Post.objects.get(id=bid)
    user = request.user
    if post.like.filter(id=request.user.id).exists():
        post.like.remove(user)
        return JsonResponse({'message': 'delete', 'like_cnt':post.like.count()})
    else:
        post.like.add(user) #like에는 게시글 정보와 user 정보가 둘 다 필요하므로 user를 넣어준다
        return JsonResponse({'message':'ok', 'like_cnt':post.like.count()})

templates/board/getdata.html
{% extends 'base_board.html' %}
{% load static %}
{% block contents %}
   <body id="page-top" style="background-color: #8C8C8C;">

<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand" href="/"><img src="{% static 'imgfile/mm2.png' %}" alt="..." /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars ms-1"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
                        {% if request.user.is_authenticated %}
                                <li class="nav-item"><a class="nav-link" href="/user/mypage">User : {{request.user}}</a></li>
                                <li class="nav-item"><a class="nav-link" href="/accounts/logout/">logout</a></li>
                        {% else %}
                                <li class="nav-item"><a class="nav-link" href="/accounts/login">login</a></li>
                                <li class="nav-item"><a class="nav-link" href="/accounts/signup">signup</a></li>
                        {% endif %}

                    </ul>
                </div>
            </div>
        </nav>
<br/><br/><br/><br/>
        <div class = "container">
            <form method="post"  enctype="multipart/form-data">
                {% csrf_token %}

                <div class="form-group">
                    <input name="title" class="form-control"  type="text" placeholder="제목을 입력해주세요"  />
                </div>
                <textarea name = "contents" id = "summernote"></textarea>
                <br/>
                <hr/>
                <input multiple type="file" name="image" accept="image/*" id="id_image">
                <div class="text-center">
                    <button class="btn btn-primary btn-xl text-uppercase" >작성 완료</button>
                </div>
            </form>
        </div>
   <script>
      $('#summernote').summernote({
        placeholder: '내용을 입력해주세요',
        tabsize: 2,
        height: 120,
        toolbar: [
          ['style', ['style']],
          ['font', ['bold', 'underline', 'clear']],
          ['color', ['color']],
          ['para', ['ul', 'ol', 'paragraph']],
          ['table', ['table']],
          ['insert', ['link', 'picture', 'video']],
          ['view', ['fullscreen', 'codeview', 'help']]
        ]
      });
    </script>
   {% endblock %}

templates/board/postresult.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="readdata" >
     {% csrf_token %}
    <button>게시판으로 가기</button>
</form>

</body>
</html>

templates/board/readData.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{% if request.user.is_authenticated %}
{{ request.user }}님은 로그인 상태 입니다 </br></br>
{% endif %}

{% for data in datas %}
{{data.id}}
<a href = "readGet/{{ data.id }}">{{ data.title }}</a>
{{ data.writer }}님의 포스트 <br/>
{% endfor %}
<a href = "/board/getdata">글 작성</a>
</body>
</html>

templates/board/readdata.html
{% extends 'base_board.html' %}
{% load static %}
{% block contents %}
    <body id="page-top" style="background-color: #8C8C8C;">

        <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
                <div class="container">
                    <a class="navbar-brand" href="/"><img src="{% static 'imgfile/mm2.png' %}" alt="..." /></a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                        Menu
                        <i class="fas fa-bars ms-1"></i>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarResponsive">
                        <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
                            {% if request.user.is_authenticated %}
                                    <li class="nav-item"><a class="nav-link" href="/user/mypage">User : {{request.user}}</a></li>
                                    <li class="nav-item"><a class="nav-link" href="/accounts/logout/">logout</a></li>
                            {% else %}
                                    <li class="nav-item"><a class="nav-link" href="/accounts/login">login</a></li>
                                    <li class="nav-item"><a class="nav-link" href="/accounts/signup">signup</a></li>
                            {% endif %}

                        </ul>
                    </div>
                </div>
            </nav>
    {% if post %}
    <section class="page-section bg-light">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <div class="modal-body">

                        <h2 class="text-uppercase">{{ post.title }}</h2>
                        <ul class="list-inline">
                            <li>
                                <strong>글쓴이:</strong>
                                {{post.writer}}
                            </li>
                            <li>
                                <strong>작성시간:</strong>
                                {{post.create_date}}
                            </li>
                        </ul>
                        <hr/>
                        <!--<img class="img-fluid d-block mx-auto" src="{%static 'imgfile/django.png' %}" alt="..." />-->
                        <p>{{ post.contents | safe }}</p>
                        <div class="text-center">
                            {% for image in post.postimage_set.all %}
                            <div style="width: 750px; height: 450px; overflow:auto">
                                <img src="/media/{{image.image}}">
                                </div>
                                <br/>
                            {% endfor %}
                            </div>
                        <br/>
                        <button class="btn btn-primary btn-xl text-uppercase" onclick="location.href='/board/readlist'" type="button">
                            <i class="fas fa-xmark me-1"></i>
                            글 닫기
                        </button>
                        &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
                        {% if request.user == post.writer %}
                        <button class="btn btn-primary btn-xl text-uppercase" onclick="location.href='/board/updateget/{{post.id}}'" type="button">
                            글 수정
                        </button>
                        <button class="btn btn-primary btn-xl text-uppercase" onclick="location.href='/board/deleteget/{{post.id}}'" type="button">
                            글 삭제
                        </button>
                        {% endif %}
                    </div>
                </div>
            </div>
            <hr/>
            {% block contents_reply %}

            {% endblock %}

            {% for reply in post.reply_set.all %}
            <hr/>
            <div class="portfolio-caption">
                <div class="portfolio-caption-heading">댓글 : {{ reply.contents }}</div>
                <hr/>
                <div class="portfolio-caption-subheading text-muted">작성자 : {{reply.writer}}</div>
                <div class="portfolio-caption-subheading text-muted">작성날짜 : {{reply.create_date}}</div>
                {% if reply.writer == request.user %}
                <a href = '/reply/deletereply/{{reply.id}}'>삭제하기</a>
                &nbsp&nbsp
                <a href = '/reply/updatereply/{{reply.id}}'>수정하기</a>
                {% endif %}
            </div>
            <hr/>

            {% endfor %}

        </div>
    </section>





    {% endif %}
    </body>




 {% endblock %}

templates/board/readget.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>


{% if post %}

    {{ post.id }}
    {{ post.title}} <br/>
    {% if post.writer == request.user %}
        <a href = "/board/updateget/{{post.id}}">수정하기</a>
        <a href = "/board/deleteget/{{post.id}}">삭제하기</a>
    {% endif %}
    {% if post.writer != request.user %}
        <a href = "/board/readdata">목록으로</a>
    {% endif %}
<br/>
<form action = "/reply/createreply/{{ post.id }}" method ="post">
{% csrf_token %}
 {{ replyform }}
    <button>save</button>
    </form>

{% for reply in post.reply_set.all %}
    {{ reply.contents }} <br/>
{% endfor %}

{% endif %}
</body>
</html>

templates/board/readlist.html
{% extends 'base_board.html' %}
{% load static %}
{% block contents %}
    <body id="page-top" >

        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand" href="/"><img src="{% static 'imgfile/mm2.png' %}" alt="..." /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars ms-1"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
                       {% if request.user.is_authenticated %}
                                <li class="nav-item"><a class="nav-link" href="/user/mypage">User : {{request.user}}</a></li>
                                <li class="nav-item"><a class="nav-link" href="/accounts/logout/">logout</a></li>
                        {% else %}
                                <li class="nav-item"><a class="nav-link" href="/accounts/login">login</a></li>
                                <li class="nav-item"><a class="nav-link" href="/accounts/signup">signup</a></li>
                        {% endif %}

                    </ul>
                </div>
            </div>
        </nav>

        <header class="masthead">
            <div class="container">
                <div class="text-center">
                    <h2 class="masthead-heading text-uppercase">게시판</h2>
                    <h4 class="section-heading text-uppercase">밑으로 스크롤해서 글을 확인하세요!</h4>
                    <h8 class="masthead-heading text-uppercase">&nbsp;</h8>
                    <div class="text-center">
                        <button class="btn btn-primary btn-xl text-uppercase" onclick="location.href='/board/getdata';">글쓰기</button>
                    </div>

                </div>
            </div>
        </header>
        <!-- 게시물 section -->
         <section class="page-section bg-light" id="portfolio">
            <div class="container">
                <div class="text-center">
                    <h2 class="section-heading text-uppercase">글 목록</h2>
                    <h3 class="section-subheading text-muted">클릭해서 확인해볼까요?</h3>
                </div>
                <div class="row">
                    {% for data in datas %}
                    <div class="col-lg-4 col-sm-6 mb-4">
                        <!-- 게시물-->
                        <div class="portfolio-item">
                            <a class="portfolio-link"  href="/board/readdata/{{data.id}}">
                                <div class="portfolio-hover">
                                    <div class="portfolio-hover-content"><i class="fas fa-plus fa-3x"></i></div>
                                </div>
                                {% if data.postimage_set %}
                                    {% for image in data.postimage_set.all|slice:":1" %}
                                            <div style="width: 280px; height: 280px; overflow: hidden">
                                                <img class="img-fluid" src="/media/{{image.image}}" alt="..." /></div>
                                    {% endfor %}
                                {% else %}
                                    <div style="width: 280px; height: 280px; overflow: hidden">
                                        <img class="img-fluid" src="{% static 'imgfile/mm2.png' %}" alt="..." /></div>
                                {% endif %}
                            </a>
                            <div class="portfolio-caption">
                                <div class="portfolio-caption-heading"> {{ data.title }}</div>
                                <div class="portfolio-caption-subheading text-muted">{{data.create_date}} {{ data.writer }}님의 글</div>

                                <div class="portfolio-caption-heading" onclick="sendRequest({{data.id}}, this)">
                                    {% if request.user in data.like.all %}
                                        ♥ {{ data.like.count }}
                                    {% else %}
                                        ♡ {{ data.like.count }}
                                    {% endif %}
                                </div>
                            </div>
                        </div>

                    </div>
                    {% endfor %}
                    <script>
                        function sendRequest(bid, event) {
                            var httpRequest = new XMLHttpRequest();
                            httpRequest.onreadystatechange = function() {
                                if (httpRequest.readyState == XMLHttpRequest.DONE && httpRequest.status == 200 ) {
                                    console.log(httpRequest.responseText);

                                    var json_data = JSON.parse(httpRequest.responseText)
                                    if(json_data['message']=='ok'){
                                        event.innerText = "♥" + json_data['like_cnt'] ;
                                    }
                                    else {
                                        event.innerText = "♡" + json_data['like_cnt'] ;
                                    }
                                }
                            };
                            httpRequest.open("GET","/like/"+bid, true);
                            httpRequest.send();
                        }
                    </script>

                </div>
            </div>
        </section>

 {% endblock %}

templates/board/updatedata.html
{% extends 'base_board.html' %}
{% load static %}
{% block contents %}
   <body id="page-top"  style="background-color: #8C8C8C;">

<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand" href="/"><img src="{% static 'imgfile/mm2.png' %}" alt="..." /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars ms-1"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
                        {% if request.user.is_authenticated %}
                                <li class="nav-item"><a class="nav-link" href="/user/mypage">User : {{request.user}}</a></li>
                                <li class="nav-item"><a class="nav-link" href="/accounts/logout/">logout</a></li>
                        {% else %}
                                <li class="nav-item"><a class="nav-link" href="/accounts/login">login</a></li>
                                <li class="nav-item"><a class="nav-link" href="/accounts/signup">signup</a></li>
                        {% endif %}

                    </ul>
                </div>
            </div>
        </nav>
<br/><br/><br/><br/>

        <div class = "container">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="form-group">
                    <input name="title" class="form-control"  type="text"  value = "{{ post.title }}" placeholder="제목을 입력해주세요"  />
                </div>
                <textarea name = "contents" id = "summernote">{{post.contents}}</textarea>
                <br/>
                <hr/>
                <input multiple type="file" name="image" accept="image/*" id="id_image">
                <div class="text-center">
                    <button class="btn btn-primary btn-xl text-uppercase" >수정 완료</button>
                </div>
            </form>
        </div>
   <script>
      $('#summernote').summernote({
        placeholder: '내용을 입력해주세요',
        tabsize: 2,
        height: 120,
        toolbar: [
          ['style', ['style']],
          ['font', ['bold', 'underline', 'clear']],
          ['color', ['color']],
          ['para', ['ul', 'ol', 'paragraph']],
          ['table', ['table']],
          ['insert', ['link', 'picture', 'video']],
          ['view', ['fullscreen', 'codeview', 'help']]
        ]
      });
    </script>
   {% endblock %}